project:
  type: website
  output-dir: docs

website:
  title: "RN"
  site-url: "https://raphael-nedellec.github.io/website"
  repo-url: "https://github.com/raphael-nedellec/website"
  repo-actions: issue
  navbar:
    title: "RAPHAEL<span class='icon-line'></span>NEDELLEC" 
    right:
      - text: "About"
        href: about.qmd

format:
  html:
    css: styles.css
    code-block-border-left: true
    smooth-scroll: true
    link-external-newwindow: true
    
editor: source

